'use client';

import { ArrowRight, ArrowUpRight, Braces, Check, CheckCircle2, Code2, DatabaseZap, Menu, MessageCircle, Moon, Network, PlugZap, Send, ShieldCheck, Sun, Workflow, Wrench, X } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';
import { FormEvent, ReactNode, useEffect, useState } from 'react';

export const navItems = [['Home', '/'], ['About', '/about'], ['Expertise', '/expertise'], ['Work', '/work'], ['Process', '/process'], ['Contact', '/contact']] as const;

export const projects = [
  { number: '01', title: 'Automated Business Data Entry', problem: 'Information must be copied between business systems, creating repetitive work and inconsistent records.', approach: 'A controlled data movement workflow that validates, transforms, and routes records between systems.', technology: 'Python, APIs, automation logic, field mapping, and data validation.', workflow: ['Source data', 'Validation', 'Transformation', 'System update'], outcome: 'Designed to reduce repetitive manual entry and improve workflow consistency.', tags: ['Python', 'APIs', 'Automation', 'Data Processing'] },
  { number: '02', title: 'AI Document Processing Workflow', problem: 'Useful information is locked in documents and must be prepared manually for downstream processes.', approach: 'A document pipeline that extracts required information and prepares dependable structured output.', technology: 'Python, OCR, AI-assisted extraction, confidence checks, and API-ready formatting.', workflow: ['Upload', 'Extraction', 'Validation', 'Structured output'], outcome: 'Designed to make document information easier to process, verify, and reuse.', tags: ['Python', 'OCR', 'AI', 'Data Extraction', 'APIs'] },
  { number: '03', title: 'CRM & Workflow Integration', problem: 'Disconnected tools require repeated updates and make it difficult to keep business information aligned.', approach: 'An event-driven integration that coordinates changes between applications without duplicate manual work.', technology: 'REST APIs, webhooks, Python transformation logic, authentication, and error handling.', workflow: ['Trigger', 'API', 'Data processing', 'CRM update', 'Notification'], outcome: 'Designed to move information reliably between systems and reduce fragmented processes.', tags: ['Python', 'REST APIs', 'Webhooks', 'Automation'] },
  { number: '04', title: 'Automated Web Workflow', problem: 'A repetitive web process must be completed through an interface that does not expose a suitable API.', approach: 'A browser automation flow with controlled interaction, observable checkpoints, and exception handling.', technology: 'Python, Playwright, page-state checks, validation, and structured data collection.', workflow: ['Browser input', 'Automation logic', 'Validation', 'Action'], outcome: 'Designed to execute repeatable browser tasks while making failures visible and recoverable.', tags: ['Python', 'Playwright', 'Browser Automation', 'Data Processing'] },
] as const;

export const expertise = [
  { icon: Network, title: 'AI Automation', text: 'Apply AI services where language, extraction, classification, or decision support adds practical value.', flow: ['Context', 'AI / API', 'Decision'] },
  { icon: Code2, title: 'Python Development', text: 'Build dependable automation logic, processing pipelines, integrations, and focused backend services.', flow: ['Input', 'Python', 'Output'] },
  { icon: Workflow, title: 'Workflow Automation', text: 'Turn repetitive business processes into clear, observable, and maintainable production workflows.', flow: ['Trigger', 'Logic', 'Action'] },
  { icon: PlugZap, title: 'API Integrations', text: 'Connect business applications, CRMs, databases, and external services through reliable APIs.', flow: ['Event', 'API', 'Sync'] },
  { icon: Braces, title: 'AI / API Systems', text: 'Combine structured business rules with AI processing, validation, and controlled downstream actions.', flow: ['Data', 'AI / API', 'Validation'] },
  { icon: DatabaseZap, title: 'Backend & Web Applications', text: 'Create focused interfaces and backend services that make automation practical for teams to operate.', flow: ['User', 'Service', 'Workflow'] },
] as const;

export const stackGroups = [
  ['Programming', ['Python', 'JavaScript', 'Dart']], ['AI & Automation', ['AI APIs', 'LLMs', 'AI Agents', 'Workflow Automation', 'Prompt Engineering']],
  ['APIs & Backend', ['REST APIs', 'FastAPI', 'Webhooks', 'Authentication', 'Firebase']], ['Web & Applications', ['Next.js', 'React', 'Flutter']],
  ['Automation & Data', ['Playwright', 'Browser Automation', 'Data Processing', 'API Automation']], ['Development', ['Git', 'GitHub', 'VS Code']],
] as const;

export const processSteps = [
  ['Discovery', 'Understand the current manual process, the business problem, the systems involved, and the required outcome.'],
  ['Workflow Mapping', 'Map triggers, inputs, decisions, integrations, failure points, and the output the workflow must produce.'],
  ['Build & Integrate', 'Develop the system with the right combination of Python, APIs, AI services, browser automation, and business tools.'],
  ['Test', 'Validate data handling, edge cases, authentication, failures, and the reliability of the complete workflow.'],
  ['Deploy & Maintain', 'Put the system where the work happens, make failures observable, and improve it as requirements evolve.'],
] as const;

export function Flow({ steps, animated = false }: { steps: readonly string[]; animated?: boolean }) { return <div className={`flow-line ${animated ? 'flow-animated' : ''}`} aria-label={steps.join(' to ')}>{steps.map((step, index) => <span className="flow-step" key={step}><b><i />{step}</b>{index < steps.length - 1 && <ArrowRight aria-hidden="true" />}</span>)}</div>; }

export function Reveal({ children, className = '', delay = 0 }: { children: ReactNode; className?: string; delay?: number }) { const reduceMotion = useReducedMotion(); return <motion.div className={className} initial={false} whileInView={reduceMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .48, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>; }

export function SiteShell({ activePath, children }: { activePath: string; children: ReactNode }) {
  const [dark, setDark] = useState(false); const [themeReady, setThemeReady] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { setDark(localStorage.getItem('theme') === 'dark'); setThemeReady(true); const onScroll = () => setScrolled(window.scrollY > 18); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
  useEffect(() => { if (!themeReady) return; document.documentElement.classList.toggle('dark', dark); localStorage.setItem('theme', dark ? 'dark' : 'light'); }, [dark, themeReady]);
  return <main className={`page page-${activePath === '/' ? 'home' : activePath.slice(1)}`}><nav className={`site-nav ${scrolled ? 'nav-scrolled' : ''}`} aria-label="Primary navigation"><a className="wordmark" href="/" onClick={() => setMenuOpen(false)}><span>MU</span><span className="wordmark-copy"><strong>Muhammad Umer</strong><small>AI Automation Engineer</small></span></a><div className="nav-links">{navItems.map(([label, href]) => <a className={activePath === href ? 'active' : ''} aria-current={activePath === href ? 'page' : undefined} href={href} key={href}>{label}</a>)}<a className="nav-cta" href="/contact">Let&apos;s Talk <ArrowUpRight size={14} /></a><button className="theme-toggle" type="button" onClick={() => setDark(v => !v)} aria-label={dark ? 'Switch to light mode' : 'Switch to dark mode'}>{dark ? <Sun size={16} /> : <Moon size={16} />}</button><button className="menu-toggle" type="button" onClick={() => setMenuOpen(v => !v)} aria-expanded={menuOpen} aria-controls="mobile-menu" aria-label={menuOpen ? 'Close navigation menu' : 'Open navigation menu'}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div><div className={`mobile-menu ${menuOpen ? 'open' : ''}`} id="mobile-menu">{navItems.map(([label, href]) => <a className={activePath === href ? 'active' : ''} aria-current={activePath === href ? 'page' : undefined} href={href} key={href} onClick={() => setMenuOpen(false)}><span>{label}</span><ArrowUpRight size={16} /></a>)}</div></nav>{children}<footer className="site-footer"><div className="footer-lead"><span className="footer-mark">MU</span><div><strong>Muhammad Umer</strong><small>AI Automation Engineer</small></div></div><nav aria-label="Footer navigation">{navItems.map(([label, href]) => <a href={href} key={href}>{label}</a>)}</nav><div className="footer-meta"><div className="footer-ctas"><a href="https://www.linkedin.com/in/itsmuhammadumer/" target="_blank" rel="noreferrer" aria-label="Connect with Muhammad Umer on LinkedIn"><ArrowUpRight size={14} /> LinkedIn</a><a href="https://wa.me/923000335194" target="_blank" rel="noreferrer" aria-label="Message Muhammad Umer on WhatsApp"><MessageCircle size={14} /> WhatsApp</a></div><span>Python · AI · APIs · Automation</span><small>© 2026 Muhammad Umer</small></div></footer></main>;
}

export function PageHeader({ kicker, title, intro }: { kicker: string; title: string; intro: string }) { return <header className="page-header"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .48 }}><p className="section-kicker">{kicker}</p><h1>{title}</h1><p className="page-intro">{intro}</p></motion.div></header>; }

export function ProfilePanel({ compact = false, editorial = false }: { compact?: boolean; editorial?: boolean }) { return <div className={`profile-panel ${compact ? 'compact' : ''} ${editorial ? 'editorial' : ''}`}><div className="profile-grid" aria-hidden="true" /><img src="/images/muhammad-umer-profile.png" alt="Muhammad Umer, AI Automation Engineer" /></div>; }

export function ExpertiseGrid({ limit }: { limit?: number }) { const items = limit ? expertise.slice(0, limit) : expertise; return <div className="expertise-grid">{items.map(({ icon: Icon, title, text, flow }) => <motion.article className="expertise-card" key={title} whileHover={{ y: -5 }} transition={{ duration: .2 }}><div className="card-top"><Icon size={20} /></div><div className="capability-body"><h3>{title}</h3><p>{text}</p></div><Flow steps={flow} /></motion.article>)}</div>; }

export function CaseStudyList({ limit }: { limit?: number }) { const items = limit ? projects.slice(0, limit) : projects; return <div className="case-study-list">{items.map(project => <motion.article className="engineering-case" key={project.number} whileHover={{ y: -3 }} transition={{ duration: .2 }}><header><h3>{project.title}</h3><span className="case-status"><i /> Documented</span></header><div className="case-core"><div className="case-problem"><h4>Problem</h4><p>{project.problem}</p></div><div className="case-approach"><h4>Approach</h4><p>{project.approach}</p></div></div><div className="case-workflow"><span>Automation flow</span><Flow steps={project.workflow} animated /></div><div className="case-lower"><div><h4>Technology</h4><p>{project.technology}</p></div><div><h4>Outcome</h4><p>{project.outcome}</p></div></div><footer><div className="tag-list">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></footer></motion.article>)}</div>; }

export function ProcessTimeline({ compact = false }: { compact?: boolean }) { const items = compact ? processSteps.slice(0, 3) : processSteps; return <div className={`timeline ${compact ? 'compact' : ''}`}>{items.map(([title, text], index) => <article className="timeline-step" key={title}><div className="timeline-number">{String(index + 1).padStart(2, '0')}<i /></div><div><h3>{title}</h3><p>{text}</p></div><Check size={16} aria-hidden="true" /></article>)}</div>; }

export function ExperienceList() { return <div className="experience-list">{['Endpoint', 'Endpointech', 'Southwest Urgent Care'].map((company, index) => <article className="experience-item" key={company}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{company}</h3></div><ArrowUpRight size={18} /></article>)}</div>; }

export const qualityItems = [{ icon: Wrench, title: 'Practical', text: 'Built around actual workflows and business problems.' }, { icon: ShieldCheck, title: 'Reliable', text: 'Tested across inputs, failures, and system boundaries.' }, { icon: CheckCircle2, title: 'Maintainable', text: 'Observable, understandable, and ready to improve.' }] as const;
export function QualityGrid() { return <div className="quality-grid">{qualityItems.map(({ icon: Icon, title, text }) => <article key={title}><div><Icon /></div><h3>{title}</h3><p>{text}</p></article>)}</div>; }
export function StackGrid({ compact = false }: { compact?: boolean }) { const groups = compact ? stackGroups.slice(0, 4) : stackGroups; return <div className={`stack-grid ${compact ? 'compact' : ''}`}>{groups.map(([category, items]) => <article className="stack-group" key={category}><header><h3>{category}</h3></header><div>{items.map(item => <b key={item}>{item}</b>)}</div></article>)}</div>; }
export function CredibilityStrip() { return <div className="credibility-strip"><span>Engineering focus</span>{['Python', 'AI Systems', 'API Integration', 'Workflow Automation'].map((item, index) => <div key={item}><i>0{index + 1}</i><strong>{item}</strong></div>)}</div>; }

export function ContactPanel() { const [formNote, setFormNote] = useState(''); const submitForm = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setFormNote('This form is ready for a contact service to be connected. No message has been sent.'); }; return <div className="contact-panel"><div className="contact-copy"><div className="contact-flow"><span>What happens next</span><Flow steps={['Context', 'Workflow map', 'Technical direction']} /></div></div><form className="contact-form" onSubmit={submitForm}><div className="form-row"><label>Name<input name="name" type="text" autoComplete="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@example.com" /></label></div><label>Workflow<textarea name="message" required rows={6} placeholder="What happens today, and where does the manual work slow things down?" /></label><button className="button button-primary" type="submit">Start a Conversation <Send size={16} /></button>{formNote && <p className="form-note" role="status">{formNote}</p>}</form></div>; }
